[package]
name = "mcp_server_shopify_dev"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/mcp_server_shopify_dev.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
